-- Hatchling Seed Data
-- Generated from packages/web/src/data/creatures.ts and packages/web/src/data/cosmetics.ts

-- Creature Definitions (115 creatures)
INSERT INTO public.creature_defs (id, name, rarity, sprite_path, description, safari_only) VALUES
(1, 'Pennypuff', 1, '/sprites/creatures/001.png', 'A small fluffy creature that collects loose change in its cheek pouches.', false),
(2, 'Budgibee', 1, '/sprites/creatures/002.png', 'A busy bee that buzzes around organizing your expenses into neat little honeycomb cells.', false),
(3, 'Savelet', 1, '/sprites/creatures/003.png', 'A tiny leaf-like critter that grows bigger each time you resist a purchase.', false),
(4, 'Cointail', 1, '/sprites/creatures/004.png', 'A squirrel-like creature with a tail shaped like a stack of coins.', false),
(5, 'Thriftpup', 1, '/sprites/creatures/005.png', 'A loyal puppy that wags its tail whenever you find a good deal.', false),
(6, 'Pigglette', 1, '/sprites/creatures/006.png', 'A miniature piggy bank creature that jingles when it walks.', false),
(7, 'Fundrop', 1, '/sprites/creatures/007.png', 'A raindrop-shaped creature that pools together with others to form savings puddles.', false),
(8, 'Dimeling', 1, '/sprites/creatures/008.png', 'A shiny little critter that rolls around like a dime on a smooth surface.', false),
(9, 'Nibblecent', 1, '/sprites/creatures/009.png', 'A hamster-like creature that nibbles away at unnecessary expenses.', false),
(10, 'Waitkin', 1, '/sprites/creatures/010.png', 'A patient little pumpkin creature that only ripens after a long wait.', false),
(11, 'Sparemite', 1, '/sprites/creatures/011.png', 'A tiny mite that feeds on spare change and grows slowly over time.', false),
(12, 'Clipkit', 1, '/sprites/creatures/012.png', 'A fox-like creature that collects coupons and clips them with its sharp teeth.', false),
(13, 'Ledgerling', 1, '/sprites/creatures/013.png', 'A bookworm creature that organizes its life in perfectly balanced ledgers.', false),
(14, 'Pennysnail', 1, '/sprites/creatures/014.png', 'A slow-moving snail with a copper-colored shell that values steady progress.', false),
(15, 'Bargainpod', 1, '/sprites/creatures/015.png', 'A seed pod creature that only blooms when it finds the best price.', false),
(16, 'Cheddamouse', 1, '/sprites/creatures/016.png', 'A mouse creature that hoards cheese-shaped gold nuggets in its tiny den.', false),
(17, 'Frugalfly', 1, '/sprites/creatures/017.png', 'A firefly whose glow brightens the more wisely you spend.', false),
(18, 'Delaybug', 1, '/sprites/creatures/018.png', 'A ladybug that encourages you to sleep on it before buying.', false),
(19, 'Nestbean', 1, '/sprites/creatures/019.png', 'A bean-shaped creature that loves building cozy little nest eggs.', false),
(20, 'Mintmoth', 1, '/sprites/creatures/020.png', 'A mint-green moth that flutters around fresh savings accounts.', false),
(21, 'Skipmunk', 1, '/sprites/creatures/021.png', 'A chipmunk that happily skips past flashy storefronts without a second look.', false),
(22, 'Waitoad', 1, '/sprites/creatures/022.png', 'A patient toad that sits on a lily pad and waits for the right moment to leap.', false),
(23, 'Stashbun', 1, '/sprites/creatures/023.png', 'A bunny that stashes acorns and coins under every bush it finds.', false),
(24, 'Ticktock', 1, '/sprites/creatures/024.png', 'A clock-shaped creature that reminds you good things come to those who wait.', false),
(25, 'Dollarbill', 1, '/sprites/creatures/025.png', 'A platypus-like creature with a flat bill that''s always counting blessings.', false),
(26, 'Pinchpenny', 1, '/sprites/creatures/026.png', 'A crab creature whose pincers are shaped like tiny pennies.', false),
(27, 'Couponix', 1, '/sprites/creatures/027.png', 'A phoenix chick that rises from clipped coupons instead of ashes.', false),
(28, 'Safelynt', 1, '/sprites/creatures/028.png', 'A lint-ball creature that gently reminds you to play it safe with spending.', false),
(29, 'Warthlrift', 1, '/sprites/creatures/029.png', 'A small warthog creature known for its thrifty nature and tough hide.', false),
(30, 'Growcoin', 1, '/sprites/creatures/030.png', 'A plant creature that sprouts coins from its branches when nurtured.', false),
(31, 'Breezebank', 1, '/sprites/creatures/031.png', 'A cloud creature that drifts along depositing savings like gentle rain.', false),
(32, 'Shufflecent', 1, '/sprites/creatures/032.png', 'A penguin-like creature that shuffles pennies into neat rows.', false),
(33, 'Bloomsave', 1, '/sprites/creatures/033.png', 'A flower that blooms brighter the longer you resist impulse purchases.', false),
(34, 'Calmchick', 1, '/sprites/creatures/034.png', 'A serene baby bird that chirps soothing melodies about financial peace.', false),
(35, 'Pouchling', 1, '/sprites/creatures/035.png', 'A kangaroo joey with an extra pouch dedicated entirely to savings.', false),
(36, 'Balancebat', 1, '/sprites/creatures/036.png', 'A bat that uses echolocation to find the perfect balance in your budget.', false),
(37, 'Dustpenny', 1, '/sprites/creatures/037.png', 'A dust bunny creature that sweeps up overlooked coins from under the couch.', false),
(38, 'Steadymole', 1, '/sprites/creatures/038.png', 'A mole that slowly but steadily tunnels toward your savings goals.', false),
(39, 'Splitcricket', 1, '/sprites/creatures/039.png', 'A cricket that chirps a reminder every time you should split the bill.', false),
(40, 'Simplebee', 1, '/sprites/creatures/040.png', 'A humble bee that finds joy in life''s simple, free pleasures.', false),
(41, 'Pebblewise', 1, '/sprites/creatures/041.png', 'A wise little pebble creature that rolls slowly toward bigger things.', false),
(42, 'Nutkeeper', 1, '/sprites/creatures/042.png', 'A squirrel that obsessively keeps count of every nut in its stash.', false),
(43, 'Dropwise', 1, '/sprites/creatures/043.png', 'A teardrop creature that knows every drop of saving adds up to an ocean.', false),
(44, 'Sparksaver', 1, '/sprites/creatures/044.png', 'A tiny spark that ignites bigger savings when given enough time.', false),
(45, 'Restbit', 1, '/sprites/creatures/045.png', 'A digital critter shaped like a pixel that rests instead of rushing.', false),
(46, 'Vaultoise', 2, '/sprites/creatures/046.png', 'A tortoise with a vault-like shell that protects your savings from impulse raids.', false),
(47, 'Coinguard', 2, '/sprites/creatures/047.png', 'An armored creature that stands watch over your coin collection day and night.', false),
(48, 'Restrainox', 2, '/sprites/creatures/048.png', 'A calm ox that teaches the art of holding back when temptation strikes.', false),
(49, 'Yieldfawn', 2, '/sprites/creatures/049.png', 'A gentle deer that grows its antlers from compound interest yields.', false),
(50, 'Bundlebear', 2, '/sprites/creatures/050.png', 'A bear cub that bundles all your small savings into one mighty hibernate stash.', false),
(51, 'Lockfin', 2, '/sprites/creatures/051.png', 'A dolphin with a padlock-shaped dorsal fin that keeps spending locked down.', false),
(52, 'Shieldrab', 2, '/sprites/creatures/052.png', 'A hermit crab whose shell is an impenetrable budget shield.', false),
(53, 'Compoundeer', 2, '/sprites/creatures/053.png', 'A reindeer whose antlers branch and multiply like compound interest.', false),
(54, 'Gardenvest', 2, '/sprites/creatures/054.png', 'A garden snake that invests its energy wisely, only striking at the right deals.', false),
(55, 'Cashawk', 2, '/sprites/creatures/055.png', 'A hawk with keen eyes that spots wasteful spending from miles away.', false),
(56, 'Dividowl', 2, '/sprites/creatures/056.png', 'A wise owl that distributes dividends of wisdom about smart money moves.', false),
(57, 'Stockpile', 2, '/sprites/creatures/057.png', 'A pile-shaped creature that grows taller with every purchase you decline.', false),
(58, 'Mintarch', 2, '/sprites/creatures/058.png', 'A monarch butterfly with wings that shimmer like freshly minted coins.', false),
(59, 'Treasurtle', 2, '/sprites/creatures/059.png', 'A sea turtle that carries a treasure chest on its back instead of a shell.', false),
(60, 'Temperbison', 2, '/sprites/creatures/060.png', 'A bison that tempers its urges and grazes only on what it truly needs.', false),
(61, 'Prudentpaw', 2, '/sprites/creatures/061.png', 'A raccoon that carefully examines every item before deciding it''s worth keeping.', false),
(62, 'Earnesteel', 2, '/sprites/creatures/062.png', 'A steel-plated creature that earns its strength through honest patience.', false),
(63, 'Interestink', 2, '/sprites/creatures/063.png', 'A skunk that sprays interest rates on anyone who tries to break their savings.', false),
(64, 'Moderacoon', 2, '/sprites/creatures/064.png', 'A raccoon that practices moderation in all things, especially shopping.', false),
(65, 'Harvestram', 2, '/sprites/creatures/065.png', 'A ram that only harvests rewards after a full season of patient waiting.', false),
(66, 'Wispling', 2, '/sprites/creatures/066.png', 'A will-o-wisp creature that wisps away urges to spend foolishly.', false),
(67, 'Fortifox', 2, '/sprites/creatures/067.png', 'A fox that fortifies its den with layers of financial security.', false),
(68, 'Rationale', 2, '/sprites/creatures/068.png', 'A rational mouse that weighs every purchase decision with scientific precision.', false),
(69, 'Acornyx', 2, '/sprites/creatures/069.png', 'A lynx that plants acorns of savings and watches them grow into mighty oaks.', false),
(70, 'Profitoad', 2, '/sprites/creatures/070.png', 'A toad whose deep croaks sound like a cash register celebrating profits.', false),
(71, 'Vaulthorn', 3, '/sprites/creatures/071.png', 'A majestic unicorn with a horn that opens any vault when savings goals are met.', false),
(72, 'Zenithrift', 3, '/sprites/creatures/072.png', 'A zen dragon that achieves inner peace through masterful thriftiness.', false),
(73, 'Bondswan', 3, '/sprites/creatures/073.png', 'An elegant swan that bonds with savers and glides across tranquil financial waters.', false),
(74, 'Pensionix', 3, '/sprites/creatures/074.png', 'A phoenix made of retirement fund statements that rises stronger with each contribution.', false),
(75, 'Goldenmane', 3, '/sprites/creatures/075.png', 'A lion with a mane woven from golden threads of disciplined saving.', false),
(76, 'Equiteer', 3, '/sprites/creatures/076.png', 'A musketeer-like creature that fights for equity and fair financial practices.', false),
(77, 'Platinumole', 3, '/sprites/creatures/077.png', 'A mole with platinum-tipped claws that digs deep into premium savings tiers.', false),
(78, 'Diamondove', 3, '/sprites/creatures/078.png', 'A dove with diamond-dusted wings that only appears to the most patient savers.', false),
(79, 'Resolute', 3, '/sprites/creatures/079.png', 'A wolf whose resolve never wavers, standing firm against every impulse purchase.', false),
(80, 'Fortunelk', 3, '/sprites/creatures/080.png', 'An elk whose antlers branch into paths of fortune for those who stay the course.', false),
(81, 'Prosperaptor', 3, '/sprites/creatures/081.png', 'A raptor that swoops in with prosperity when your patience finally pays off.', false),
(82, 'Wealtheel', 3, '/sprites/creatures/082.png', 'An electric eel that channels wealth energy through its disciplined currents.', false),
(83, 'Sapphsiren', 3, '/sprites/creatures/083.png', 'A sapphire siren that sings songs of financial wisdom to guide you through storms.', false),
(84, 'Gratifowl', 3, '/sprites/creatures/084.png', 'An owl made of gratitude feathers that hoots wisdom about appreciating what you have.', false),
(85, 'Enduraflame', 3, '/sprites/creatures/085.png', 'A flame creature that burns steadily for years, never flickering from short-term temptation.', false),
(86, 'Empiregg', 4, '/sprites/creatures/086.png', 'A golden egg dragon that hatches empires from decades of patient investment.', false),
(87, 'Aurumodon', 4, '/sprites/creatures/087.png', 'An ancient mastodon made entirely of aurum gold, walking treasury of the ages.', false),
(88, 'Titanvest', 4, '/sprites/creatures/088.png', 'A titan clad in investment armor that grows more powerful with each market cycle.', false),
(89, 'Eternabull', 4, '/sprites/creatures/089.png', 'An eternal bull that charges through bear markets with unwavering optimism.', false),
(90, 'Inheritrix', 4, '/sprites/creatures/090.png', 'A mystical fox that passes down financial wisdom through generations.', false),
(91, 'Abundragon', 4, '/sprites/creatures/091.png', 'A dragon that breathes abundance on those who master the art of delayed gratification.', false),
(92, 'Legaclaw', 4, '/sprites/creatures/092.png', 'A gryphon whose legacy claws carve prosperity into the stone of time.', false),
(93, 'Sovereignowl', 4, '/sprites/creatures/093.png', 'A sovereign owl wearing a crown forged from lifetimes of prudent decisions.', false),
(94, 'Dividendrake', 4, '/sprites/creatures/094.png', 'A drake that rains dividends from the sky like a golden thunderstorm.', false),
(95, 'Fortresso', 4, '/sprites/creatures/095.png', 'A living fortress creature whose walls are built from years of unshakeable savings.', false),
(96, 'Mythifrugal', 5, '/sprites/creatures/096.png', 'The ultimate being of frugality, said to exist only in legends whispered by the wisest savers.', false),
(97, 'Cosmovault', 5, '/sprites/creatures/097.png', 'A cosmic vault entity that holds the savings of entire universes within its core.', false),
(98, 'Eternisave', 5, '/sprites/creatures/098.png', 'A timeless being born from an eternity of patient saving, older than money itself.', false),
(99, 'Infinivest', 5, '/sprites/creatures/099.png', 'An infinite investment spirit whose returns compound across dimensions and timelines.', false),
(100, 'Gratificrown', 5, '/sprites/creatures/100.png', 'The crowned deity of delayed gratification, rewarding only those with ultimate patience.', false),
(101, 'Wildsave', 1, '/sprites/creatures/101.png', 'A wild chipmunk found only in the safari, gathering savings from the untamed wilderness.', true),
(102, 'Junglecent', 1, '/sprites/creatures/102.png', 'A vine creature that swings through the safari canopy collecting forgotten cents.', true),
(103, 'Savannickel', 1, '/sprites/creatures/103.png', 'A meerkat that stands guard over nickels hidden in the savanna sand.', true),
(104, 'Fernfrugal', 1, '/sprites/creatures/104.png', 'A fern sprite that unfurls its fronds to reveal tiny savings in the wild.', true),
(105, 'Trailpenny', 1, '/sprites/creatures/105.png', 'A hedgehog that leaves a trail of pennies wherever it roams in the safari.', true),
(106, 'Canopycash', 2, '/sprites/creatures/106.png', 'A tree frog that stores cash reserves in hollowed-out canopy branches.', true),
(107, 'Riverich', 2, '/sprites/creatures/107.png', 'An otter that dives into safari rivers and resurfaces with gleaming treasure.', true),
(108, 'Thornvault', 2, '/sprites/creatures/108.png', 'A thorny armadillo whose spiky shell doubles as an impenetrable savings vault.', true),
(109, 'Misthoard', 2, '/sprites/creatures/109.png', 'A misty gecko that hoards treasures deep within the safari fog where no one can find them.', true),
(110, 'Emberwild', 3, '/sprites/creatures/110.png', 'A wild fire fox found only in volcanic safari zones, its embers forge pure gold.', true),
(111, 'Oasissafe', 3, '/sprites/creatures/111.png', 'A mystical oasis guardian that protects the most precious savings in the desert safari.', true),
(112, 'Thundersave', 3, '/sprites/creatures/112.png', 'A storm eagle that rides safari thunderclouds and strikes down reckless spending.', true),
(113, 'Eldervault', 4, '/sprites/creatures/113.png', 'An ancient tree spirit of the deep safari whose roots connect to vaults across the world.', true),
(114, 'Primevalcoin', 4, '/sprites/creatures/114.png', 'A dinosaur-like creature from the primeval safari, its scales are the first coins ever minted.', true),
(115, 'Ultimawild', 5, '/sprites/creatures/115.png', 'The supreme guardian of the safari realm, a shape-shifting entity that embodies all savings wisdom of the wild.', true)
;

-- Cosmetic Definitions (20 items)
INSERT INTO public.cosmetic_defs (id, name, category, sprite_path, price, description) VALUES
(1, 'Top Hat', 'hat', '/sprites/cosmetics/hat-tophat.png', 2000, 'A distinguished pixel top hat.'),
(2, 'Crown', 'hat', '/sprites/cosmetics/hat-crown.png', 5000, 'A golden crown fit for a savings monarch.'),
(3, 'Party Hat', 'hat', '/sprites/cosmetics/hat-party.png', 1500, 'Celebrate your self-control!'),
(4, 'Cowboy Hat', 'hat', '/sprites/cosmetics/hat-cowboy.png', 3000, 'Yeehaw! Wrangle those impulse purchases.'),
(5, 'Wizard Hat', 'hat', '/sprites/cosmetics/hat-wizard.png', 4000, 'Channel ancient frugality magic.'),
(6, 'Pixel Sunglasses', 'accessory', '/sprites/cosmetics/acc-sunglasses.png', 1500, 'Too cool to impulse buy.'),
(7, 'Red Scarf', 'accessory', '/sprites/cosmetics/acc-scarf.png', 2000, 'A warm scarf for cold turkey shopping bans.'),
(8, 'Bow Tie', 'accessory', '/sprites/cosmetics/acc-bowtie.png', 1000, 'Dapper and debt-free.'),
(9, 'Cape', 'accessory', '/sprites/cosmetics/acc-cape.png', 3500, 'Every savings hero needs a cape.'),
(10, 'Monocle', 'accessory', '/sprites/cosmetics/acc-monocle.png', 2500, 'For inspecting deals with discernment.'),
(11, 'Pixel Meadow', 'background', '/sprites/cosmetics/bg-meadow.png', 3000, 'A peaceful green meadow.'),
(12, 'Starry Night', 'background', '/sprites/cosmetics/bg-stars.png', 4000, 'A sky full of savings stars.'),
(13, 'Ocean Waves', 'background', '/sprites/cosmetics/bg-ocean.png', 3500, 'Calm waters of financial peace.'),
(14, 'Pixel Forest', 'background', '/sprites/cosmetics/bg-forest.png', 3000, 'A lush forest of growing savings.'),
(15, 'Cozy Room', 'background', '/sprites/cosmetics/bg-room.png', 5000, 'A warm room — no shopping needed.'),
(16, 'Sparkles', 'effect', '/sprites/cosmetics/fx-sparkles.png', 2000, 'Glittering particles of restraint.'),
(17, 'Hearts', 'effect', '/sprites/cosmetics/fx-hearts.png', 2000, 'Love for your bank account.'),
(18, 'Fire Aura', 'effect', '/sprites/cosmetics/fx-fire.png', 4500, 'Your savings streak is on fire!'),
(19, 'Bubbles', 'effect', '/sprites/cosmetics/fx-bubbles.png', 1500, 'Floating bubbles of joy.'),
(20, 'Lightning', 'effect', '/sprites/cosmetics/fx-lightning.png', 5000, 'Electrifying willpower.')
;
